// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"time"

	"github.com/guregu/null"
)

type Comment struct {
	ID            int32
	Commenttext   string
	Postedon      time.Time
	Threadid      int32
	Parentcomment null.Int
	Author        string
}

type Thread struct {
	ID         int32
	Title      string
	Threadtext string
	Postedon   time.Time
	Author     string
}

type ThreadsTag struct {
	Threadid int32
	Tagtext  string
}

type User struct {
	Username string
	Pw       string
}
